build: false
clone_folder: C:\projects\me-cms
platform: x86

environment:
  db_dsn: 'mysql://root:Password12!@localhost/test'
  THUMBER_DRIVER: "gd"
  global:
    PHP: "C:/PHP"

services:
  - mysql

init:
  - SET PATH=C:\php\;%PATH%
  - SET PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%

before_test:
  - mysqladmin --host=localhost --user=root --password=Password12! create test

install:
  - cd c:\
  - curl -fsS -o php.zip https://windows.php.net/downloads/releases/latest/php-7.3-nts-Win32-VC15-x86-latest.zip
  - 7z x php.zip -oc:\php > nul
  - cd c:\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_pdo_pgsql.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - cd C:\projects\me-cms
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist --no-interaction --ansi --no-progress

test_script:
  - cd C:\projects\me-cms
  - vendor\bin\phpunit.bat

